import { PERMISSION } from '../../domain/roles.js';
import { needsAttention } from '../../domain/workflow.js';

/**
 * «Курс молодого бойца» — вводный тур при первом входе в CRM.
 * Шаг: section — раздел в шапке карточки, route — куда перейти (строка или функция от данных),
 * target — [data-tour] подсвечиваемого элемента (нет — карточка по центру),
 * expand — [data-tour] свёрнутого меню, которое нужно раскрыть перед шагом,
 * cue — анимация-подсказка, описанная данными (см. cues.js), permission — показывать не всем.
 * Тексты — коротко: что это, зачем и что нажать.
 */

/** Карточка для знакомства: сначала незавершённая и срочная — на ней видны все кнопки. */
const sampleInteraction = ({ rows }) => {
  const open = rows.filter((row) => !row.completedAt);
  const row = open.find((item) => needsAttention(item.sla)) ?? open[0];
  return row ? `/interactions/${row.id}` : '/interactions';
};

const SECTION = {
  start: 'Знакомство',
  dashboard: 'Дашборд',
  search: 'Поиск и ИИ',
  interactions: 'Взаимодействия',
  card: 'Карточка вуза',
  analytics: 'Аналитика',
  reports: 'Отчёты',
  data: 'Данные',
  admin: 'Управление',
  finish: 'Финиш',
};

export const TOUR_STEPS = [
  {
    id: 'welcome',
    section: SECTION.start,
    route: '/',
    title: 'Добро пожаловать в CRM ИТ Школы',
    text: 'Покажем каждый раздел и каждую важную кнопку: где ваши вузы, как вести этапы, собирать отчёты и что умеет ИИ-помощник. Листайте стрелками ← → на клавиатуре, Esc — выйти.',
    cue: { type: 'burst', colors: ['brand', 'accent'], count: 18 },
  },
  {
    id: 'sidebar',
    section: SECTION.start,
    route: '/',
    target: 'sidebar',
    placement: 'right',
    title: 'Меню разделов',
    text: 'Все разделы — слева: сверху ежедневная работа, ниже «Данные» — аналитика, отчёты и справочники. Активный раздел подсвечен фиолетовым.',
    cue: { type: 'sweep', axis: 'y' },
  },
  {
    id: 'profile',
    section: SECTION.start,
    route: '/',
    target: 'profile',
    placement: 'right',
    title: 'Ваш профиль',
    text: 'Имя и роль: от роли зависит, какие разделы и вузы вам видны. Нажмите на профиль — откроются настройки: аватарка, отключение анимаций, стартовая страница, горячие клавиши. Кнопка справа — выйти.',
    cue: { type: 'pointer', click: false },
  },

  {
    id: 'dashboard-actions',
    section: SECTION.dashboard,
    route: '/',
    target: 'dashboard-actions',
    placement: 'bottom',
    title: 'Быстрые действия',
    text: '«Новое взаимодействие» — начать работу с вузом прямо с главной. Если у вас есть права на импорт, рядом будет «Импортировать» — загрузка данных из Excel.',
    cue: { type: 'pointer', click: true },
  },
  {
    id: 'stage-stats',
    section: SECTION.dashboard,
    route: '/',
    target: 'stage-stats',
    placement: 'bottom',
    title: 'Распределение по этапам',
    text: 'Сколько заявок на каждом из 14 этапов, сгруппированных в фазы: знакомство, договор, внедрение, обучение. Наведите на столбец или сектор — увидите этап и число.',
    cue: { type: 'sweep', axis: 'x' },
  },
  {
    id: 'kpi',
    section: SECTION.dashboard,
    route: '/',
    target: 'kpi',
    placement: 'right',
    title: 'Ключевые показатели',
    text: 'Вузы в работе, договоры за месяц и актуализированные программы. Наведите на заголовок любого блока — всплывёт подсказка, что именно считается.',
    cue: { type: 'pulse', repeat: 2 },
  },
  {
    id: 'attention',
    section: SECTION.dashboard,
    route: '/',
    target: 'attention',
    placement: 'left',
    title: 'С чего начать день',
    text: 'Этапы, у которых вышел или подходит срок, — самые срочные сверху. Нажмите на вуз, чтобы открыть карточку, или «Все срочные» — полный список.',
    cue: { type: 'pulse', repeat: 2 },
  },
  {
    id: 'activity',
    section: SECTION.dashboard,
    route: '/',
    target: 'activity',
    placement: 'left',
    title: 'Последние действия',
    text: 'Лента изменений: кто перевёл этап, оставил комментарий или приложил файл. Нажмите на запись — откроется карточка вуза.',
    cue: { type: 'sweep', axis: 'y' },
  },
  {
    id: 'dashboard-table',
    section: SECTION.dashboard,
    route: '/',
    target: 'dashboard-table',
    placement: 'top',
    title: 'Свежие заявки',
    text: 'Последние заявки вузов: продукт и направление, статус этапа, ответственный менеджер и дата обновления.',
    cue: { type: 'sweep', axis: 'x' },
  },

  {
    id: 'search',
    section: SECTION.search,
    route: '/',
    target: 'search',
    placement: 'bottom',
    title: 'Поиск по всей системе',
    text: 'Найдёт раздел, блок на странице или статью справки. Если ответа нет — нажмите Enter, и вопрос уйдёт ИИ-помощнику.',
    cue: { type: 'typing', text: 'Как сформировать отчёт?' },
  },
  {
    id: 'search-hotkey',
    section: SECTION.search,
    route: '/',
    target: 'search-hotkey',
    placement: 'bottom',
    title: 'Горячие клавиши',
    text: 'Ctrl + K (⌘ + K на Mac) — открыть поиск с любой страницы. Ctrl + / — сразу перейти в чат с помощником.',
    cue: { type: 'pulse', repeat: 2 },
  },
  {
    id: 'assistant',
    section: SECTION.search,
    route: '/',
    target: 'open-chat',
    placement: 'bottom',
    title: 'ИИ-помощник',
    text: 'Объяснит, как что-то сделать, или сделает сам: «Отчёт по КФУ за март в PDF», «Покажи просроченные», «Как дела у ИТМО?».',
    cue: { type: 'pointer', click: true },
  },

  {
    id: 'nav-interactions',
    section: SECTION.interactions,
    route: '/interactions',
    target: 'nav:/interactions',
    placement: 'right',
    title: 'Раздел «Взаимодействия»',
    text: 'Главный рабочий список: каждая строка — работа с вузом по направлению и продукту. Оранжевое число — сколько этапов требуют внимания.',
    cue: { type: 'pulse', repeat: 2 },
  },
  {
    id: 'filters-search',
    section: SECTION.interactions,
    route: '/interactions',
    target: 'filters-search',
    placement: 'bottom',
    title: 'Быстрый поиск по списку',
    text: 'Начните вводить название вуза, программы или продукта — список сузится сразу, без нажатия Enter.',
    cue: { type: 'typing', text: 'ИТМО' },
  },
  {
    id: 'filters-button',
    section: SECTION.interactions,
    route: '/interactions',
    target: 'filters-button',
    placement: 'bottom',
    title: 'Фильтры',
    text: 'Откроет панель: период, вузы, направления, продукты, ответственные, этапы и «только требующие внимания». Число на кнопке — сколько фильтров включено. Фильтры запоминаются.',
    cue: { type: 'pointer', click: true },
  },
  {
    id: 'view',
    section: SECTION.interactions,
    route: '/interactions',
    target: 'view-toggle',
    placement: 'bottom',
    title: 'Доска или таблица',
    text: 'Список открывается доской этапов. «Таблица» покажет те же взаимодействия строками — там есть сортировка: сначала срочные, недавно изменённые, по вузу или по этапу. Выбор запомнится.',
    cue: { type: 'pointer', click: true },
  },
  {
    id: 'interactions-list',
    section: SECTION.interactions,
    route: '/interactions',
    target: 'interactions-list',
    placement: 'top',
    title: 'Доска этапов',
    text: 'Колонки — этапы по фазам. Перетащите карточку вуза в следующую колонку — откроется окно смены этапа с комментарием и файлами. Нажмите на карточку — откроется вуз, его мы сейчас и посмотрим.',
    cue: { type: 'sweep', axis: 'y' },
  },
  {
    id: 'new-interaction',
    section: SECTION.interactions,
    route: '/interactions',
    target: 'new-interaction',
    placement: 'bottom',
    title: 'Новое взаимодействие',
    text: 'Выберите вуз, направление, программу, продукт и ответственного — работа начнётся с первого этапа «Поиск контактов».',
    cue: { type: 'pulse', repeat: 1 },
  },

  {
    id: 'card-change-stage',
    section: SECTION.card,
    route: sampleInteraction,
    target: 'card-change-stage',
    placement: 'bottom',
    title: 'Сменить этап',
    text: 'Вперёд — на следующий этап, комментарий по желанию. Назад на доработку или пропуск необязательного этапа — только с комментарием.',
    cue: { type: 'pointer', click: true },
  },
  {
    id: 'card-stage',
    section: SECTION.card,
    route: sampleInteraction,
    target: 'card-stage',
    placement: 'bottom',
    title: 'Текущий этап и срок',
    text: 'Где сейчас работа, что сделать на этапе, с какого числа он идёт и сколько дней осталось по нормативу. Просрочка подсвечивается.',
    cue: { type: 'sweep', axis: 'x' },
  },
  {
    id: 'card-history',
    section: SECTION.card,
    route: sampleInteraction,
    target: 'card-history',
    placement: 'right',
    title: 'История и файлы',
    text: 'Вкладка «История» — комментарии и все переходы, здесь же пишут новый комментарий и прикладывают файлы. «Файлы» — документы, разложенные по этапам.',
    cue: { type: 'sweep', axis: 'y' },
  },
  {
    id: 'card-params',
    section: SECTION.card,
    route: sampleInteraction,
    target: 'card-params',
    placement: 'left',
    title: 'Характеристики заявки',
    text: 'Вуз, ИТ-направление, учебная программа, продукт, набор этапов и данные договора — всё в одном блоке.',
    cue: { type: 'pulse', repeat: 1 },
  },
  {
    id: 'card-people',
    section: SECTION.card,
    route: sampleInteraction,
    target: 'card-people',
    placement: 'left',
    title: 'Ответственные',
    text: 'Кто ведёт вуз со стороны ИТ Школы и контактные лица вуза. Руководитель может назначить другого менеджера.',
    cue: { type: 'pulse', repeat: 1 },
  },
  {
    id: 'card-path',
    section: SECTION.card,
    route: sampleInteraction,
    target: 'card-path',
    placement: 'left',
    title: 'Путь взаимодействия',
    text: 'Все этапы по порядку: пройденные отмечены, текущий выделен. Видно, сколько осталось до конца.',
    cue: { type: 'sweep', axis: 'y' },
  },

  {
    id: 'report-pin',
    section: SECTION.analytics,
    route: '/analytics',
    target: 'report-pin',
    placement: 'left',
    title: 'Графики и кнопка «В отчёт»',
    text: 'Показатели считаются по фильтрам сверху. Кнопка в углу карточки добавляет её в начало PDF-отчёта.',
    cue: { type: 'pointer', click: true },
  },
  {
    id: 'analytics-customize',
    section: SECTION.analytics,
    route: '/analytics',
    target: 'analytics-customize',
    placement: 'bottom',
    title: 'Своя панель',
    text: 'Шестерёнка включает редактирование: перетаскивайте виджеты, меняйте размер, убирайте лишние и добавляйте новые из каталога.',
    cue: { type: 'pointer', click: true },
  },
  {
    id: 'analytics-export',
    section: SECTION.analytics,
    route: '/analytics',
    target: 'analytics-export',
    placement: 'bottom',
    title: 'Скачать панель в PDF',
    text: 'Сохраняет всю панель с текущими фильтрами одним файлом — удобно отправить руководителю.',
    cue: { type: 'pulse', repeat: 1 },
  },

  {
    id: 'report-step-1',
    section: SECTION.reports,
    route: '/reports',
    target: 'report-step-1',
    placement: 'right',
    title: 'Шаг 1. Период и фильтры',
    text: 'Какие взаимодействия попадут в отчёт: период, вузы, направления, продукты и ответственные. Число под заголовком — сколько строк получится.',
    cue: { type: 'sweep', axis: 'x' },
  },
  {
    id: 'report-step-2',
    section: SECTION.reports,
    route: '/reports',
    target: 'report-step-2',
    placement: 'right',
    title: 'Шаг 2. Колонки',
    text: 'Отметьте нужные данные. Первые пять — стандартный набор; справа сразу обновляется предпросмотр.',
    cue: { type: 'sweep', axis: 'y' },
  },
  {
    id: 'report-step-3',
    section: SECTION.reports,
    route: '/reports',
    target: 'report-step-3',
    placement: 'right',
    title: 'Шаг 3. Графики',
    text: 'Сюда попадают карточки, отмеченные в «Аналитике» кнопкой «В отчёт». Их можно переставить или убрать — в PDF они окажутся в начале.',
    cue: { type: 'pulse', repeat: 1 },
  },
  {
    id: 'report-step-4',
    section: SECTION.reports,
    route: '/reports',
    target: 'report-step-4',
    placement: 'right',
    title: 'Шаг 4. Формат и название',
    text: 'XLSX или XLS — для работы в таблицах, PDF — для печати и отправки. Название станет именем файла.',
    cue: { type: 'pointer', click: true },
  },
  {
    id: 'report-submit',
    section: SECTION.reports,
    route: '/reports',
    target: 'report-submit',
    placement: 'top',
    title: 'Скачать отчёт',
    text: 'Файл скачивается сразу — ничего не нужно печатать или сохранять вручную.',
    cue: { type: 'pointer', click: true },
  },
  {
    id: 'report-history',
    section: SECTION.reports,
    route: '/reports',
    target: 'report-history',
    placement: 'top',
    title: 'История отчётов',
    text: 'Каждый отчёт сохраняется с фильтрами и колонками. Кнопка в строке соберёт его заново по свежим данным.',
    cue: { type: 'sweep', axis: 'x' },
  },

  {
    id: 'catalogs',
    section: SECTION.data,
    route: '/catalogs',
    target: 'catalogs-head',
    placement: 'bottom',
    title: 'Справочники',
    text: 'Единые списки вузов, направлений, программ, продуктов и контактов. Вкладки переключают справочник, поиск справа — ищет внутри.',
    cue: { type: 'sweep', axis: 'x' },
  },
  {
    id: 'import',
    section: SECTION.data,
    route: '/import',
    target: 'import-steps',
    placement: 'bottom',
    permission: PERMISSION.importCatalogs,
    title: 'Импорт из Excel и CSV',
    text: 'Четыре шага: файл → сопоставление колонок → проверка → загрузка. Мастер покажет, что изменится, а загрузку можно отменить целиком. Шаблон — кнопкой справа сверху.',
    cue: { type: 'sweep', axis: 'x' },
  },

  {
    id: 'settings',
    section: SECTION.admin,
    route: '/',
    target: 'nav-settings-group',
    expand: 'nav-settings',
    placement: 'right',
    permission: PERMISSION.manageWorkflows,
    title: 'Меню «Настройки»',
    text: 'Раскрывается по нажатию: этапы работы, интеграции, пользователи и журнал действий — в зависимости от ваших прав.',
    cue: { type: 'pulse', repeat: 1 },
  },
  {
    id: 'workflows',
    section: SECTION.admin,
    route: '/workflows',
    target: 'workflow-stages',
    placement: 'right',
    permission: PERMISSION.manageWorkflows,
    title: 'Этапы работы',
    text: 'Названия, порядок, фазы и нормативные сроки этапов. Стрелками этап двигают, галочкой делают необязательным. Для другой аудитории можно завести отдельный набор.',
    cue: { type: 'sweep', axis: 'y' },
  },
  {
    id: 'workflow-save',
    section: SECTION.admin,
    route: '/workflows',
    target: 'workflow-save',
    placement: 'top',
    permission: PERMISSION.manageWorkflows,
    title: 'Сохранить или отменить',
    text: 'Изменения не применяются, пока вы не нажмёте «Сохранить». «Отменить изменения» вернёт всё как было.',
    cue: { type: 'pointer', click: false },
  },
  {
    id: 'integrations',
    section: SECTION.admin,
    route: '/integrations',
    target: 'integration-inbox',
    placement: 'top',
    permission: PERMISSION.manageIntegrations,
    title: 'Интеграции с LMS и сайтом',
    text: 'Сверху — источники и кнопка синхронизации. «Входящие записи» нужно разобрать: привязать к существующему взаимодействию или создать новое.',
    cue: { type: 'sweep', axis: 'y' },
  },
  {
    id: 'users',
    section: SECTION.admin,
    route: '/users',
    target: 'users-add',
    placement: 'bottom',
    permission: PERMISSION.manageTeamAccounts,
    title: 'Пользователи и доступ',
    text: 'Добавьте сотрудника — система выдаст временный пароль. В таблице меняют роль, видимость вузов и блокируют доступ.',
    cue: { type: 'pointer', click: true },
  },
  {
    id: 'audit',
    section: SECTION.admin,
    route: '/audit',
    target: 'audit-filters',
    placement: 'bottom',
    permission: PERMISSION.viewAudit,
    title: 'Журнал действий',
    text: 'Кто, что и когда менял. Ищите по действию или объекту и фильтруйте по сотрудникам. Записи нельзя изменить.',
    cue: { type: 'sweep', axis: 'x' },
  },

  {
    id: 'help',
    section: SECTION.finish,
    route: '/help',
    target: 'help',
    placement: 'right',
    title: 'Справка всегда рядом',
    text: 'Статьи со скриншотами по каждому разделу, коды ошибок и контакты поддержки.',
    cue: { type: 'pointer', click: false },
  },
  {
    id: 'help-restart',
    section: SECTION.finish,
    route: '/help',
    target: 'help-restart',
    placement: 'bottom',
    title: 'Пройти курс заново',
    text: 'Забыли, где что? Эта кнопка запустит курс ещё раз — с любого шага можно выйти клавишей Esc.',
    cue: { type: 'pulse', repeat: 2 },
  },
  {
    id: 'finish',
    section: SECTION.finish,
    route: '/',
    title: 'Курс пройден!',
    text: 'Вы знаете всё, чтобы начать. Если что-то забудется — спросите ИИ-помощника или загляните в справку. Удачной работы с вузами!',
    cue: { type: 'fireworks' },
  },
];

export const stepsFor = (can) => TOUR_STEPS.filter((step) => !step.permission || can(step.permission));
