import { PERMISSION } from '../../domain/roles.js';

/**
 * «Курс молодого бойца» — вводный тур при первом входе в CRM.
 * Шаг: route — куда перейти, target — [data-tour] подсвечиваемого элемента (нет — карточка по центру),
 * cue — анимация-подсказка, описанная данными (см. cues.js), permission — показывать не всем.
 * Тексты — коротко: что это и зачем, одно действие на шаг.
 */
export const TOUR_STEPS = [
  {
    id: 'welcome',
    route: '/',
    title: 'Добро пожаловать в CRM ИТ Школы',
    text: 'За пару минут покажем главное: где ваши вузы, как переводить этапы, собирать отчёты и что умеет ИИ-помощник. Курс можно пропустить в любой момент.',
    cue: { type: 'burst', colors: ['brand', 'accent'], count: 18 },
  },
  {
    id: 'sidebar',
    route: '/',
    target: 'sidebar',
    placement: 'right',
    title: 'Меню разделов',
    text: 'Все разделы — слева. Оранжевое число у «Взаимодействий» — сколько этапов требуют внимания прямо сейчас.',
    cue: { type: 'sweep', axis: 'y' },
  },
  {
    id: 'attention',
    route: '/',
    target: 'attention',
    placement: 'left',
    title: 'С чего начать день',
    text: 'Здесь этапы, у которых вышел или подходит срок. Самые срочные — сверху: нажмите на вуз, чтобы открыть карточку.',
    cue: { type: 'pulse', repeat: 2 },
  },
  {
    id: 'search',
    route: '/',
    target: 'search',
    placement: 'bottom',
    title: 'Поиск по всей системе',
    text: 'Найдёт раздел, блок или статью справки. Ctrl + K — открыть поиск с клавиатуры. Enter — задать вопрос ИИ-помощнику.',
    cue: { type: 'typing', text: 'Как сформировать отчёт?' },
  },
  {
    id: 'assistant',
    route: '/',
    target: 'open-chat',
    placement: 'bottom',
    title: 'ИИ-помощник',
    text: 'Объяснит, как что-то сделать, или сделает сам: «Отчёт по КФУ за март в PDF», «Покажи просроченные», «Как дела у ИТМО?».',
    cue: { type: 'pointer', click: true },
  },
  {
    id: 'filters',
    route: '/interactions',
    target: 'filters',
    placement: 'bottom',
    title: 'Взаимодействия с вузами',
    text: 'Поиск и фильтры по периоду, вузам, направлениям, продуктам и этапам. Фильтры запоминаются — вернётесь туда же.',
    cue: { type: 'sweep', axis: 'x' },
  },
  {
    id: 'view',
    route: '/interactions',
    target: 'view-toggle',
    placement: 'bottom',
    title: 'Таблица или доска',
    text: 'На доске этапов карточки можно перетаскивать мышью — откроется окно смены этапа с комментарием и файлами.',
    cue: { type: 'pointer', click: true },
  },
  {
    id: 'new-interaction',
    route: '/interactions',
    target: 'new-interaction',
    placement: 'bottom',
    title: 'Новое взаимодействие',
    text: 'Выберите вуз, направление, программу, продукт и ответственного — работа начнётся с первого этапа.',
    cue: { type: 'pulse', repeat: 1 },
  },
  {
    id: 'analytics',
    route: '/analytics',
    target: 'report-pin',
    placement: 'left',
    title: 'Аналитика и «В отчёт»',
    text: 'Графики и показатели считаются по фильтрам. Кнопка в углу карточки добавляет её в начало PDF-отчёта.',
    cue: { type: 'pointer', click: true },
  },
  {
    id: 'reports',
    route: '/reports',
    target: 'report-step-1',
    placement: 'right',
    title: 'Отчёты за пару кликов',
    text: 'Период и фильтры → колонки → графики → формат XLSX, XLS или PDF. Файл скачивается сразу и остаётся в истории.',
    cue: { type: 'sweep', axis: 'y' },
  },
  {
    id: 'import',
    route: '/interactions',
    target: 'nav:/import',
    placement: 'right',
    permission: PERMISSION.importCatalogs,
    title: 'Импорт из Excel и CSV',
    text: 'Загрузите вузы и договоры из файла: мастер покажет, что изменится, а загрузку можно отменить целиком.',
    cue: { type: 'pulse', repeat: 1 },
  },
  {
    id: 'settings',
    route: '/interactions',
    target: 'nav-settings',
    placement: 'right',
    permission: PERMISSION.manageTeamAccounts,
    title: 'Сотрудники и настройки',
    text: 'В «Настройках» — этапы работы, интеграции, журнал и «Пользователи и доступ»: здесь создают учётные записи и выдают пароли.',
    cue: { type: 'pulse', repeat: 1 },
  },
  {
    id: 'help',
    route: '/interactions',
    target: 'help',
    placement: 'right',
    title: 'Справка всегда рядом',
    text: 'Подробные статьи со скриншотами по каждому разделу. Этот курс можно пройти заново там же.',
    cue: { type: 'pointer', click: false },
  },
  {
    id: 'finish',
    route: '/',
    title: 'Готово! Можно работать',
    text: 'Если что-то забудется — спросите ИИ-помощника или загляните в справку. Удачной работы с вузами!',
    cue: { type: 'burst', colors: ['accent', 'brand'], count: 28 },
  },
];

export const stepsFor = (can) => TOUR_STEPS.filter((step) => !step.permission || can(step.permission));
