/**
 * Все иконки приложения — из @atomaro/icons (дизайн-система Ростелекома).
 * Реэкспорт из одного места: проще заменить иконку во всём продукте и видно, что уже используется.
 *
 * Импорт поштучный: пакет собран в CommonJS, и импорт из индекса группы
 * (`@atomaro/icons/24/action`) затягивает в бандл сотни неиспользуемых иконок.
 * Все модули проходят через interopDefault — см. lib/interopDefault.js.
 */
import { interopDefault } from '../lib/interopDefault.js';
import AddLargeModule from '@atomaro/icons/24/action/AddLarge';
import AttachmentModule from '@atomaro/icons/24/action/Attachment';
import CatalogModule from '@atomaro/icons/24/action/Catalog';
import CheckEditModule from '@atomaro/icons/24/action/CheckEdit';
import DownloadModule from '@atomaro/icons/24/action/Download';
import HomeModule from '@atomaro/icons/24/action/Home';
import ChecklistModule from '@atomaro/icons/24/action/Checklist';
import LinkModule from '@atomaro/icons/24/action/Link';
import RefreshModule from '@atomaro/icons/24/action/Refresh';
import SearchModule from '@atomaro/icons/24/action/Search';
import SettingsModule from '@atomaro/icons/24/action/Settings';
import SecurityCheckModule from '@atomaro/icons/24/action/SecurityCheck';
import SynchronizationModule from '@atomaro/icons/24/action/Synchronization';
import TrashModule from '@atomaro/icons/24/action/Trash';
import UploadModule from '@atomaro/icons/24/action/Upload';
import FilterModule from '@atomaro/icons/24/action/Filter';
import ErrorMonochromeModule from '@atomaro/icons/24/alert/ErrorMonochrome';
import HelpStrokeModule from '@atomaro/icons/24/alert/HelpStroke';
import InformationMonochromeModule from '@atomaro/icons/24/alert/InformationMonochrome';
import OkMonochromeModule from '@atomaro/icons/24/alert/OkMonochrome';
import AttentionMonochromeModule from '@atomaro/icons/24/alert/AttentionMonochrome';
import StatisticsColumnModule from '@atomaro/icons/24/business/StatisticsColumn';
import CalendarModule from '@atomaro/icons/24/communication/Calendar';
import HistoryModule from '@atomaro/icons/24/communication/History';
import MailModule from '@atomaro/icons/24/communication/Mail';
import CallModule from '@atomaro/icons/24/communication/Call';
import UserModule from '@atomaro/icons/24/communication/User';
import UsersModule from '@atomaro/icons/24/communication/Users';
import EducationModule from '@atomaro/icons/24/culture/Education';
import GovernmentModule from '@atomaro/icons/24/culture/Government';
import PulseModule from '@atomaro/icons/24/culture/Pulse';
import DocumentTextModule from '@atomaro/icons/24/document/DocumentText';
import TableModule from '@atomaro/icons/24/document/Table';
import XlsxModule from '@atomaro/icons/24/document/XLSX';
import MarketingFunnelModule from '@atomaro/icons/24/editor/MarketingFunnel';
import ArrowDownModule from '@atomaro/icons/24/navigation/ArrowDown';
import ArrowLeftModule from '@atomaro/icons/24/navigation/ArrowLeft';
import ArrowRightModule from '@atomaro/icons/24/navigation/ArrowRight';
import ArrowUpModule from '@atomaro/icons/24/navigation/ArrowUp';
import CheckSmallModule from '@atomaro/icons/24/navigation/CheckSmall';
import CheckLargeModule from '@atomaro/icons/24/navigation/CheckLarge';
import ChevronDownModule from '@atomaro/icons/24/navigation/ChevronDown';
import ChevronRightModule from '@atomaro/icons/24/navigation/ChevronRight';
import CloseSmallModule from '@atomaro/icons/24/navigation/CloseSmall';
import MenuModule from '@atomaro/icons/24/navigation/Menu';
import MoreModule from '@atomaro/icons/24/navigation/More';
import SignOutModule from '@atomaro/icons/24/navigation/SignOut';
import ServerModule from '@atomaro/icons/24/technology/Server';
import CopyModule from '@atomaro/icons/24/action/Copy';
import SendModule from '@atomaro/icons/24/action/Send';
import StopStrokeModule from '@atomaro/icons/24/alert/StopStroke';
import ChatModule from '@atomaro/icons/24/communication/Chat';
import MaximizeModule from '@atomaro/icons/24/media/Maximize';
import MinimizeModule from '@atomaro/icons/24/media/Minimize';
import MicrophoneModule from '@atomaro/icons/24/media/Microphone';
import VolumeUpModule from '@atomaro/icons/24/media/VolumeUp';
import MagicModule from '@atomaro/icons/24/technology/Magic';

export const AddIcon = interopDefault(AddLargeModule);
export const AttachmentIcon = interopDefault(AttachmentModule);
export const CatalogIcon = interopDefault(CatalogModule);
export const EditIcon = interopDefault(CheckEditModule);
export const DownloadIcon = interopDefault(DownloadModule);
export const HomeIcon = interopDefault(HomeModule);
export const InteractionsIcon = interopDefault(ChecklistModule);
export const LinkIcon = interopDefault(LinkModule);
export const RefreshIcon = interopDefault(RefreshModule);
export const SearchIcon = interopDefault(SearchModule);
export const SettingsIcon = interopDefault(SettingsModule);
export const ShieldIcon = interopDefault(SecurityCheckModule);
export const SyncIcon = interopDefault(SynchronizationModule);
export const TrashIcon = interopDefault(TrashModule);
export const UploadIcon = interopDefault(UploadModule);
export const FilterIcon = interopDefault(FilterModule);
export const ErrorIcon = interopDefault(ErrorMonochromeModule);
export const HelpIcon = interopDefault(HelpStrokeModule);
export const InfoIcon = interopDefault(InformationMonochromeModule);
export const SuccessIcon = interopDefault(OkMonochromeModule);
export const WarningIcon = interopDefault(AttentionMonochromeModule);
export const AnalyticsIcon = interopDefault(StatisticsColumnModule);
export const CalendarIcon = interopDefault(CalendarModule);
export const HistoryIcon = interopDefault(HistoryModule);
export const MailIcon = interopDefault(MailModule);
export const PhoneIcon = interopDefault(CallModule);
export const UserIcon = interopDefault(UserModule);
export const UsersIcon = interopDefault(UsersModule);
export const EducationIcon = interopDefault(EducationModule);
export const UniversityIcon = interopDefault(GovernmentModule);
export const PulseIcon = interopDefault(PulseModule);
export const DocumentIcon = interopDefault(DocumentTextModule);
export const ReportIcon = interopDefault(TableModule);
export const XlsxIcon = interopDefault(XlsxModule);
export const WorkflowIcon = interopDefault(MarketingFunnelModule);
export const ArrowDownIcon = interopDefault(ArrowDownModule);
export const ArrowLeftIcon = interopDefault(ArrowLeftModule);
export const ArrowRightIcon = interopDefault(ArrowRightModule);
export const ArrowUpIcon = interopDefault(ArrowUpModule);
export const CheckIcon = interopDefault(CheckSmallModule);
export const CheckLargeIcon = interopDefault(CheckLargeModule);
export const ChevronDownIcon = interopDefault(ChevronDownModule);
export const ChevronRightIcon = interopDefault(ChevronRightModule);
export const CloseIcon = interopDefault(CloseSmallModule);
export const MenuIcon = interopDefault(MenuModule);
export const MoreIcon = interopDefault(MoreModule);
export const SignOutIcon = interopDefault(SignOutModule);
export const IntegrationIcon = interopDefault(ServerModule);
export const CopyIcon = interopDefault(CopyModule);
export const SendIcon = interopDefault(SendModule);
export const StopIcon = interopDefault(StopStrokeModule);
export const ChatIcon = interopDefault(ChatModule);
export const MaximizeIcon = interopDefault(MaximizeModule);
export const MinimizeIcon = interopDefault(MinimizeModule);
export const MicrophoneIcon = interopDefault(MicrophoneModule);
export const VolumeIcon = interopDefault(VolumeUpModule);
export const MagicIcon = interopDefault(MagicModule);
